### PR TITLE
HW1

### PR DESCRIPTION
**Pull request by huhuhu0420**
only add readme and rename the folder

(I don't know what else can put in readme)

### CODE REVIEW

**Review by x06lan — DISMISSED** [review]

**Review by nonorze-VOXX — DISMISSED** [review]

**Comment by x06lan** [comment]
I prefer move  shell folder to hw1/project1 or something instead of make it stand alone.
Maybe remove hw1.zip since we need zip our hw1 anyway

**Comment by huhuhu0420** [comment]
1. 3.p5 rename to 3.p1 
2. rm .zip
3. doc有需要寫kernel版本嗎，應該每個人都不一樣

**Comment by huhuhu0420** [comment]
> I prefer move shell folder to hw1/project1 or something instead of make it stand alone. 

I can't understand 😦

**Comment by x06lan** [comment]
> > I prefer move shell folder to hw1/project1 or something instead of make it stand alone.
> 
> I can't understand 😦

forget about it

**Comment by x06lan** [comment]
> 1. 3.p5 rename to 3.p1
> 
>     2. rm .zip
> 
>     3. doc有需要寫kernel版本嗎，應該每個人都不一樣

LGTM

**Review by x06lan — APPROVED** [review]

**Pull request merged**
