### PR TITLE
hw2 ch5 part2

### LINKED ISSUE #11: P3-2. Scheduling Algorithms
This project involves implementing several process scheduling algorithms:
* Round-Robin
* Priority with round-robin

### PR DESCRIPTION
**Pull request by OuChiaYun**
RR.c
linklist.h
priority_RR.c
queue.h

我想說同一個ch5，文件就直接更新在x06lan 的readme 了

### CODE REVIEW

**Comment by huhuhu0420** [comment]
should update Makefile to
```
all:
	gcc FCFS.c -o FCFS.out
	gcc SJF.c -o SJF.out
	gcc priority.c -o priority.out
	gcc RR.c -o RR.out
	gcc priority_RR.c -o priority_RR.out
clean:
	rm *.out
```

**Review by x06lan — CHANGES_REQUESTED** [review]
# Priority order is wrong
> Priorities range from 1 to 10, where a higher numeric value indicates a higher
relative priority. 

screenshot-2024-04-22-13-47-01

# RR and PriorityRR quantum time is wrong
> For round-robin scheduling, the length of a time quantum is
10 milliseconds

**Comment by OuChiaYun** [comment]
> should update Makefile to
> 
> ```
> all:
> 	gcc FCFS.c -o FCFS.out
> 	gcc SJF.c -o SJF.out
> 	gcc priority.c -o priority.out
> 	gcc RR.c -o RR.out
> 	gcc priority_RR.c -o priority_RR.out
> clean:
> 	rm *.out
> ```

done.

**Comment by OuChiaYun** [comment]
> # Priority order is wrong
> > Priorities range from 1 to 10, where a higher numeric value indicates a higher
> > relative priority.
> 
> screenshot-2024-04-22-13-47-01
> 
> # RR and PriorityRR quantum time is wrong
> > For round-robin scheduling, the length of a time quantum is
> > 10 milliseconds

done

**Comment by OuChiaYun** [comment]
> # Priority order is wrong
> > Priorities range from 1 to 10, where a higher numeric value indicates a higher
> > relative priority.
> 
> screenshot-2024-04-22-13-47-01
> 
> # RR and PriorityRR quantum time is wrong
> > For round-robin scheduling, the length of a time quantum is
> > 10 milliseconds

done.

**Comment by OuChiaYun** [comment]
> # Priority order is wrong
> > Priorities range from 1 to 10, where a higher numeric value indicates a higher
> > relative priority.
> 
done.
> screenshot-2024-04-22-13-47-01
> 
> # RR and PriorityRR quantum time is wrong
> > For round-robin scheduling, the length of a time quantum is
> > 10 milliseconds

**Review by x06lan — APPROVED** [review]

**Pull request merged**
