### PR TITLE
Ch5-1

### LINKED ISSUE #10: P3-1 Scheduling Algorithms
This project involves implementing several process scheduling algorithms:
* FCFS
* SJF
* Priority-based

### PR DESCRIPTION
**Pull request by x06lan**
- FCFS
- SJF
- Priority-based

### CODE REVIEW

**Review by huhuhu0420 — CHANGES_REQUESTED** [review]
Calculate the average turnaround time, waiting time, and response time for each of the scheduling algorithms.

**Comment by nonorze-VOXX** [comment]
fix #10 
link #10

**Review by nonorze-VOXX — CHANGES_REQUESTED** [review]
arrive look no use 
other part LGTM

**Comment by huhuhu0420** [comment]
@OuChiaYun why close 🤔

**Review by nonorze-VOXX — DISMISSED** [review]

**Review by OuChiaYun — DISMISSED** [review]

**Comment by x06lan** [comment]
> Calculate the average turnaround time, waiting time, and response time for each of the scheduling algorithms.

done

**Comment by huhuhu0420** [comment]
Looks good. But forgot to update readme.

**Comment by x06lan** [comment]
> Looks good. But forgot to update readme.

done

**Review by huhuhu0420 — APPROVED** [review]

**Pull request merged**
